#include <Geode/Geode.hpp>
#include <Geode/modify/PlayLayer.hpp>
#include <Geode/modify/CCScheduler.hpp>
#include <Geode/modify/PauseLayer.hpp>

using namespace geode::prelude;

bool g_show_menu = false;
bool g_freeze = false;
bool g_show_hitboxes = false;
float g_speedhack = 1.0f;

class $modify(MyPlayLayer, PlayLayer) {
	    bool init(GJGameLevel* level, bool useReplay) {
	    	        if (!PlayLayer::init(level, useReplay)) return false;
	    	                this->m_fields->m_showHitboxes = g_show_hitboxes;
	    	                        return true;
	    	                            }

	    	                                void update(float dt) {
	    	                                	        if (g_freeze) {
	    	                                	        	            PlayLayer::update(0.0f);
	    	                                	        	                    } else {
	    	                                	        	                    	            PlayLayer::update(dt);
	    	                                	        	                    	                    }
	    	                                	        	                    	                        }
	    	                                	        	                    	                        };

	    	                                	        	                    	                        class $modify(CCScheduler) {
	    	                                	        	                    	                        	    void update(float dt) {
	    	                                	        	                    	                        	    	        CCScheduler::update(dt * g_speedhack);
	    	                                	        	                    	                        	    	            }
	    	                                	        	                    	                        	    	            };

	    	                                	        	                    	                        	    	            class $modify(MyPauseLayer, PauseLayer) {
	    	                                	        	                    	                        	    	            	    void customSetup() {
	    	                                	        	                    	                        	    	            	    	        PauseLayer::customSetup();

	    	                                	        	                    	                        	    	            	    	                auto menu = this->getChildByID("right-button-menu");
	    	                                	        	                    	                        	    	            	    	                        if (!menu) menu = this->getChildByID("left-button-menu");

	    	                                	        	                    	                        	    	            	    	                                if (menu) {
	    	                                	        	                    	                        	    	            	    	                                	            auto label = CCLabelBMFont::create("MyMod", "goldFont.fnt");
	    	                                	        	                    	                        	    	            	    	                                	                        label->setScale(0.6f);
	    	                                	        	                    	                        	    	            	    	                                	                                    auto btn = CCMenuItemSpriteExtra::create(
	    	                                	        	                    	                        	    	            	    	                                	                                    	                label, 
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                this, 
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                menu_selector(MyPauseLayer::onOpenCheatMenu)
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                            );
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                        menu->addChild(btn);
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                    menu->updateLayout();
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                            }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                }

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    void onOpenCheatMenu(CCObject* sender) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	        g_show_menu = !g_show_menu;
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	            }

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                void onQuit(CCObject* sender) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        geode::createQuickPopup(
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	            "Выход",
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                        "Реально хочешь выйти, бро?",
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                    "Да", "Остаться",
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                [this, sender](auto, bool btn2) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                if (!btn2) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                    PauseLayer::onQuit(sender);
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                    }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                        );
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            };

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            #include <Geode/modify/ImGuiLayer.hpp>
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            class $modify(ImGuiLayer) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    void draw() {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	        ImGuiLayer::draw();
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                if (!g_show_menu) return;

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                        ImGui::SetNextWindowSize({300, 250}, ImGuiCond_FirstUseEver);
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                ImGui::Begin("Sam's Cool Menu", &g_show_menu);

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                        ImGui::Text("Настройки тренировки:");
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                ImGui::Separator();

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                        ImGui::Checkbox("Заморозить кубик", &g_freeze);

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                if (ImGui::Checkbox("Показать хитбоксы", &g_show_hitboxes)) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            if (auto pl = PlayLayer::get()) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                pl->m_fields->m_showHitboxes = g_show_hitboxes;
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                            }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                    }

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                            ImGui::SliderFloat("Скорость игры", &g_speedhack, 0.1f, 3.0f);
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    if (ImGui::Button("Сбросить скорость")) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	            g_speedhack = 1.0f;
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                    }

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                            ImGui::Separator();
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    if (ImGui::Button("Закрыть меню")) {
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    	            g_show_menu = false;
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    	                    }

	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    	                            ImGui::End();
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    	                                }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    	                                };
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    	                                
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    	                                    }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            	                                                    }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                	            }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    	                                                                }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            	    }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                	                                                            }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                	                }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        	                                                }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                	        )
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    	                }
	    	                                	        	                    	                        	    	            	    	                                	                                    	                                                                                                    }
	    	                                	        	                    	                        	    	            	    	                                	                                    )
	    	                                	        	                    	                        	    	            	    	                                }
	    	                                	        	                    	                        	    	            	    }
	    	                                	        	                    	                        	    	            }
	    	                                	        	                    	                        	    }
	    	                                	        	                    	                        }
	    	                                	        	                    }
	    	                                	        }
	    	                                }
	    }
}
